import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import elements from bootstrap
import { Container, Row, Col, Button } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });
// import redux
import { useSelector, useDispatch } from "react-redux";
import { increment, decrement } from "@/store/features/counter/counterSlice";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";

export default function Home() {
  const dispatch = useDispatch();

  const count = useSelector((state: any) => state.counter.value);
  return (
    <>
      <Head>
        <title>Red Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Row>
            <Col xs={12} md={6}>
              <h1>Red Template</h1>
            </Col>
            <Col xs={12} md={6}>
              <h1>@ Red Template</h1>
            </Col>
          </Row>
        </Container>
        <Button variant="primary">Primary</Button>

        <Container>
          <Row>
            <Col xs={12} md={6}>
              <h3>REDUX</h3>

              <div>
                <div>
                  <div>
                    <button
                      aria-label="Increment value"
                      onClick={() => dispatch(increment())}
                    >
                      Increment
                    </button>
                    <span>{count}</span>
                    <button
                      aria-label="Decrement value"
                      onClick={() => dispatch(decrement())}
                    >
                      Decrement
                    </button>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>

        <h3>SWIPER</h3>
        <Swiper
          spaceBetween={50}
          slidesPerView={3}
          onSlideChange={() => console.log("slide change")}
          onSwiper={(swiper) => console.log(swiper)}
        >
          <SwiperSlide>Slide 1</SwiperSlide>
          <SwiperSlide>Slide 2</SwiperSlide>
          <SwiperSlide>Slide 3</SwiperSlide>
          <SwiperSlide>Slide 4</SwiperSlide>
        </Swiper>
      </main>
    </>
  );
}
